---
version: '3.8'
services:
  hub:
    image: selenium/hub
    ports:
      - 4444:4444
    networks:
      - abc
  chrome:
    image: selenium/node-chrome-debug
    ports:
      - 5901:5900
    environment:
      HUB_HOST: hub
    links:
      - hub
    networks:
      - xyz
  firefox:
    image: selenium/node-firefox-debug
    ports:
      - 5902:5900
    environment:
      HUB_HOST: hub
    links:
      - hub
    networks:
      - xyz
networks:
  abc: {}
  xyz: {}
...



